version: '3.4'
services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    platform: linux/amd64
    command: jekyll serve --watch --verbose --incremental
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll